"""V17 PART 4 — dynamic AI content + a large curated Persian fallback pool.

Primary: each mesh message is generated by the existing AI key pool with a per-number
persona and a short per-edge running history, so exchanges are coherent, asymmetric,
multi-turn Persian dialogues.

Fallback (AI unavailable / over budget / timeout): draw from a LARGE curated Persian
phrase pool (>=500 entries) assembled from hardcoded category templates with slots
(name / time-of-day / product) and randomized assembly, so even the fallback is
non-repeating. The pool is a HARDCODED CONSTANT built at import — it never depends on a
DB seed succeeding (the V16 lesson).

Anti-repeat: per-edge used-hash tracking + a near-duplicate similarity check reject exact
and near-exact repeats; light punctuation variation is a second defense.
"""
from __future__ import annotations
import difflib
import hashlib
import logging
import random

logger = logging.getLogger("afrakala.warmup.content")

# ── Category templates (hardcoded seeds for the combinatorial pool) ──────────
GREETINGS = [
    "سلام", "سلام وقت بخیر", "درود", "سلام دوست من", "سلام همکار عزیز",
    "درود بر شما", "سلام خوبی؟", "سلام حالتون چطوره", "وقت بخیر", "سلام و ارادت",
    "سلام رفیق", "درود و احترام", "سلام حال شما", "سلام روزتون بخیر", "سلام صبح بخیر",
]

TIMES_OF_DAY = ["صبح بخیر", "ظهر بخیر", "عصر بخیر", "شب بخیر", "روز خوبی داشته باشید"]

SMALL_TALK = [
    "امیدوارم حالت خوب باشه", "روزت پربرکت باشه", "کار و بار چطوره",
    "بازار این روزها چطوره", "خدا قوت بده", "امیدوارم بازار خوب باشه",
    "چه خبرا از بازار", "این هفته سرت شلوغه؟", "امیدوارم فروش خوب باشه",
    "همه چی رو به راهه؟", "خسته نباشی", "دمت گرم بابت همکاری",
    "حالت رو خوب کنه خدا", "امیدوارم بهت خوش بگذره", "روزهای خوبی پیش رو داشته باشی",
    "کارها روی روال افتاده؟", "امیدوارم حال دلت خوب باشه", "چطور می‌گذره روزها",
    "امیدوارم سرحال باشی", "همه چیز خوب پیش میره ان‌شاءالله",
]

QUESTIONS = [
    "قیمت یخچال ساید امروز چنده", "کولر گازی ۱۸۰۰۰ موجود داری",
    "لیست جدید رو فرستادی؟", "ماشین لباسشویی چند مدل داری",
    "این ماه تخفیف ویژه‌ای دارین؟", "بار جدید کی می‌رسه",
    "اجاق گاز فردار موجوده؟", "قیمت‌ها تغییری کرده این هفته؟",
    "چند تا برند تلویزیون داری", "همکاری عمده هم انجام می‌دی؟",
    "تسویه نقدی تخفیف داره؟", "ارسال به شهرستان دارین",
    "موجودی انبار به‌روزه؟", "پکیج دیواری هم می‌فروشی",
    "جاروبرقی صنعتی داری", "گارانتی محصولات چطوره",
    "امکان مرجوعی هست؟", "حداقل سفارش چند تاست",
    "فاکتور رسمی می‌دین؟", "کاتالوگ امسال آماده شده؟",
]

CONFIRMATIONS = [
    "بله حتماً در خدمتم", "چشم همین الان می‌فرستم", "آره موجوده",
    "بله بفرمایید", "حتماً، چند لحظه", "درسته همینطوره",
    "بله در خدمت شما هستم", "قربانت، انجام میشه", "بله فردا آماده‌ست",
    "چشم یادداشت کردم", "بله همکاری می‌کنیم", "حتماً پیگیری می‌کنم",
    "بله حله", "درسته، تایید شد", "چشم روی چشم",
]

FOLLOW_UPS = [
    "بعداً بیشتر صحبت می‌کنیم", "فردا هماهنگ می‌کنم باهات",
    "لیست رو شب می‌فرستم", "یه سر بزن فروشگاه", "بعد از ظهر تماس می‌گیرم",
    "قیمت نهایی رو میگم بهت", "هماهنگی رو انجام میدم", "خبرش رو بهت میدم",
    "منتظر جوابت می‌مونم", "پیگیر سفارش هستم", "تا آخر هفته آماده میشه",
    "بارت رو کنار گذاشتم", "به‌محض رسیدن بار خبر میدم", "فاکتور رو آماده می‌کنم",
    "شماره‌ت رو ذخیره کردم",
]

SHOP_TALK = [
    "بازار لوازم خانگی این روزها داغه", "قیمت دلار روی همه چی اثر گذاشته",
    "برند جنرال این فصل فروشش خوبه", "ساید بای ساید تقاضاش بالا رفته",
    "کولر گازی الان فصلشه", "اسنوا و جی‌پلاس بار جدید آوردن",
    "مشتری‌ها دنبال تخفیف نقدی‌ان", "ارسال شهرستان یکم گرون شده",
    "پکیج دیواری فروشش خوب شده", "تلویزیون‌های بزرگ متقاضی داره",
    "اجاق گاز رومیزی زیاد می‌خوان", "لباسشویی دوقلو طرفدار داره",
    "بازار عمده‌فروشی رقابتی شده", "جنس اصل همیشه مشتری داره",
    "گارانتی معتبر خیلی مهم شده", "انبار رو باید شارژ کنیم",
    "تسویه‌ها این ماه بهتر شده", "همکارها بار مشترک می‌گیرن",
    "قیمت‌ها هر روز تغییر می‌کنه", "فروش آنلاین هم راه انداختیم",
    "مشتری وفادار ارزش داره", "کیفیت رو فدای قیمت نمی‌کنیم",
    "بار چینی و ایرانی هر دو داریم", "تنوع محصول زیاد شده",
    "نمایشگاه امسال شلوغ بود",
]

EMOJI_ONLY = [
    "👍", "🙏", "🌹", "😊", "👌", "💪", "🌟", "🔥", "✅", "🤝",
    "👍👍", "🙏🌹", "😊🙏", "💐", "☕", "🌷", "❤️", "👏", "🫡", "🥰",
]

# Slot markers that assemble() fills in.
NAME_SLOT = "{name}"
PRODUCT_SLOT = "{product}"

SLOTTED = [
    "{name} جان، {product} موجوده؟",
    "سلام {name}، قیمت {product} رو داری؟",
    "{name} عزیز، بار {product} کی می‌رسه؟",
    "برای {name} جان بگم که {product} آماده‌ست",
    "{name} جان خسته نباشی، {product} چطوره",
]

PRODUCTS = [
    "یخچال ساید", "کولر گازی", "ماشین لباسشویی", "تلویزیون ۵۵ اینچ",
    "اجاق گاز", "پکیج دیواری", "جاروبرقی", "ماکروویو", "آبگرمکن", "کولر آبی",
]


def _build_pool() -> list[str]:
    """Deterministically assemble a large, de-duplicated Persian phrase pool (>=500)
    from the hardcoded category seeds above. Pure — no RNG, no DB, no network."""
    pool: list[str] = []
    seen: set[str] = set()

    def _add(s: str):
        s = " ".join(s.split()).strip()
        if s and s not in seen:
            seen.add(s)
            pool.append(s)

    # Standalone category entries.
    for lst in (GREETINGS, TIMES_OF_DAY, SMALL_TALK, QUESTIONS, CONFIRMATIONS,
                FOLLOW_UPS, SHOP_TALK, EMOJI_ONLY):
        for s in lst:
            _add(s)

    # greeting × question   (e.g. "سلام، قیمت یخچال ساید امروز چنده")
    for g in GREETINGS:
        for q in QUESTIONS:
            _add(f"{g}، {q}")
    # greeting × small talk
    for g in GREETINGS:
        for s in SMALL_TALK:
            _add(f"{g}، {s}")
    # greeting × shop talk
    for g in GREETINGS[:8]:
        for s in SHOP_TALK:
            _add(f"{g}، {s}")
    # small talk × follow up
    for s in SMALL_TALK[:10]:
        for f in FOLLOW_UPS:
            _add(f"{s}. {f}")
    return pool


# HARDCODED CONSTANT — built once at import from the seeds above. Never DB-dependent.
FALLBACK_PHRASES: list[str] = _build_pool()


def content_hash(text: str) -> str:
    """Stable hash of a normalized message, for per-edge anti-repeat tracking."""
    return hashlib.sha256(normalize_text(text).encode("utf-8")).hexdigest()[:16]


def normalize_text(text: str) -> str:
    """Lowercase-ish normalization: collapse whitespace, strip common punctuation so
    near-duplicates that differ only by spacing/punctuation compare equal."""
    t = (text or "").strip()
    for ch in "،.!?؟…:؛\n\t":
        t = t.replace(ch, " ")
    return " ".join(t.split())


def is_near_duplicate(candidate: str, recent: list[str], threshold: float = 0.82) -> bool:
    """True if `candidate` is an exact or near-duplicate of anything in `recent`
    (difflib ratio on normalized text). Second-defense against repetitive fingerprints."""
    cand = normalize_text(candidate)
    if not cand:
        return True
    for r in recent:
        rn = normalize_text(r)
        if not rn:
            continue
        if cand == rn:
            return True
        if difflib.SequenceMatcher(None, cand, rn).ratio() >= threshold:
            return True
    return False


def _apply_variation(text: str, rng: random.Random) -> str:
    """Light, human-plausible punctuation/emoji variation as a second anti-repeat defense."""
    tails = ["", "", " 🙏", " 👍", " 🌹", ".", " ..."]
    return text + rng.choice(tails)


def assemble_fallback_message(recent_hashes: set[str] | None = None,
                              name: str | None = None,
                              product: str | None = None,
                              rng: random.Random | None = None,
                              max_tries: int = 40) -> str:
    """Pick a non-repeating fallback phrase (optionally filling name/product slots) that
    is not already in `recent_hashes`. Never touches the DB — works even with an empty
    DB phrase table."""
    r = rng or random
    recent_hashes = recent_hashes or set()

    # Occasionally use a slotted, personalized template.
    use_slot = bool(name) and r.random() < 0.35
    for _ in range(max_tries):
        if use_slot:
            tmpl = r.choice(SLOTTED)
            msg = tmpl.replace(NAME_SLOT, name or "").replace(
                PRODUCT_SLOT, product or r.choice(PRODUCTS))
        else:
            msg = r.choice(FALLBACK_PHRASES)
            if name and r.random() < 0.25:
                msg = f"{name} جان، {msg}"
        msg = _apply_variation(msg, r)
        if content_hash(msg) not in recent_hashes:
            return msg
    # Extremely unlikely: pool exhausted for this edge — return a varied phrase anyway.
    return _apply_variation(r.choice(FALLBACK_PHRASES), r)


async def generate_mesh_message(*, persona: str | None = None,
                                history: list[str] | None = None,
                                recent_hashes: set[str] | None = None,
                                name: str | None = None,
                                product: str | None = None,
                                ai_fn=None,
                                rng: random.Random | None = None,
                                max_ai_tries: int = 2) -> tuple[str, str]:
    """Generate one mesh message. Returns (text, source) where source is "ai" or
    "fallback". Tries the AI generator first (if provided); on failure, timeout, empty,
    or a near-duplicate result, falls back to the curated pool. The result is always
    checked against `recent_hashes`/`history` for anti-repeat."""
    history = history or []
    recent_hashes = recent_hashes or set()
    r = rng or random

    if ai_fn is not None:
        for _ in range(max_ai_tries):
            try:
                text = await ai_fn(persona=persona, history=history, name=name, product=product)
            except Exception as e:
                logger.debug("mesh AI generation failed, will fall back: %s", e)
                break
            if not text or not text.strip():
                break
            text = text.strip()
            if content_hash(text) in recent_hashes or is_near_duplicate(text, history):
                continue  # retry the AI once more before falling back
            return text, "ai"

    return assemble_fallback_message(recent_hashes=recent_hashes, name=name,
                                     product=product, rng=r), "fallback"
