"""V17 PART 4 — dynamic AI content + a large curated Persian fallback pool.

Primary: each mesh message is generated by the existing AI key pool with a per-number
persona and a short per-edge running history, so exchanges are coherent, asymmetric,
multi-turn Persian dialogues.

Fallback (AI unavailable / over budget / timeout): draw from a LARGE curated Persian
phrase pool (>=500 entries) assembled from hardcoded category templates with slots
(name / time-of-day / product) and randomized assembly, so even the fallback is
non-repeating. The pool is a HARDCODED CONSTANT built at import — it never depends on a
DB seed succeeding (the V16 lesson).

Anti-repeat: per-edge used-hash tracking + a near-duplicate similarity check reject exact
and near-exact repeats; light punctuation variation is a second defense.
"""
from __future__ import annotations
import difflib
import hashlib
import logging
import random
import re

logger = logging.getLogger("afrakala.warmup.content")

# ── Safety: never let an internal identifier reach a warm-up message ──────────
# Warm-up runs between our OWN accounts; there is no real "recipient". The only
# names that may ever appear are realistic human first names from this curated
# pool — NEVER an account number, instance id, phone number, or system label like
# "9048249533 گوشی زینب شخصی". A message containing any digit run that looks like a
# phone/instance id, or any chunk of a known account identifier, is rejected.
HUMAN_NAMES = [
    "رضا", "علی", "مریم", "زهرا", "حسین", "محمد", "فاطمه", "سارا", "نیما", "مهدی",
    "الهام", "کیوان", "نگار", "امیر", "بهنام", "شیرین", "پویا", "لیلا", "سعید", "مینا",
    "آرش", "نازنین", "کامران", "پریسا", "حامد", "مهسا", "بابک", "رعنا", "فرهاد", "سمیرا",
]

# Persian/Arabic-Indic → ASCII digits, so "۹۰۴۸۲۴۹۵۳۲" is caught just like "9048249532".
_DIGIT_MAP = str.maketrans("۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩", "01234567890123456789")

# A run of >=7 consecutive digits looks like a phone number / instance id — never a
# legitimate product number (e.g. "کولر گازی ۱۸۰۰۰" is only 5 digits, "۵۵ اینچ" is 2).
_LONG_DIGIT_RUN = re.compile(r"\d{7,}")


def _to_ascii_digits(s: str) -> str:
    return (s or "").translate(_DIGIT_MAP)


def looks_like_identifier(text: str) -> bool:
    """True if `text` contains a digit run resembling a phone number or instance id."""
    return bool(_LONG_DIGIT_RUN.search(_to_ascii_digits(text)))


def message_is_safe(text: str, forbidden=()) -> bool:
    """Hard filter run on EVERY warm-up message before it is sent (AI or fallback).

    Rejects the text if it (a) is empty, (b) contains any long digit run that looks
    like a phone/instance id, or (c) contains a chunk of a known internal identifier or
    label passed in `forbidden` (the account number/instance_id/phone/name of either
    side of the edge). This is the last line of defense so a leaked identifier never
    ships even if the persona/history somehow reintroduced one."""
    if not text or not text.strip():
        return False
    norm = _to_ascii_digits(text).lower()
    if _LONG_DIGIT_RUN.search(norm):
        return False
    for f in forbidden:
        if not f:
            continue
        fn = _to_ascii_digits(str(f)).lower().strip()
        if not fn:
            continue
        # Any digit chunk (>=4) from an identifier must not appear verbatim.
        for chunk in re.findall(r"\d{4,}", fn):
            if chunk in norm:
                return False
        # Any distinctive non-numeric label token (>=3 chars) must not appear, so
        # "گوشی زینب شخصی" can never surface even split into words.
        for tok in re.split(r"[\s،,.\-_/|]+", fn):
            if len(tok) >= 3 and not tok.isdigit() and tok in norm:
                return False
    return True

# ── Category templates (hardcoded seeds for the combinatorial pool) ──────────
GREETINGS = [
    "سلام", "سلام وقت بخیر", "درود", "سلام دوست من", "سلام همکار عزیز",
    "درود بر شما", "سلام خوبی؟", "سلام حالتون چطوره", "وقت بخیر", "سلام و ارادت",
    "سلام رفیق", "درود و احترام", "سلام حال شما", "سلام روزتون بخیر", "سلام صبح بخیر",
]

TIMES_OF_DAY = ["صبح بخیر", "ظهر بخیر", "عصر بخیر", "شب بخیر", "روز خوبی داشته باشید"]

SMALL_TALK = [
    "امیدوارم حالت خوب باشه", "روزت پربرکت باشه", "کار و بار چطوره",
    "بازار این روزها چطوره", "خدا قوت بده", "امیدوارم بازار خوب باشه",
    "چه خبرا از بازار", "این هفته سرت شلوغه؟", "امیدوارم فروش خوب باشه",
    "همه چی رو به راهه؟", "خسته نباشی", "دمت گرم بابت همکاری",
    "حالت رو خوب کنه خدا", "امیدوارم بهت خوش بگذره", "روزهای خوبی پیش رو داشته باشی",
    "کارها روی روال افتاده؟", "امیدوارم حال دلت خوب باشه", "چطور می‌گذره روزها",
    "امیدوارم سرحال باشی", "همه چیز خوب پیش میره ان‌شاءالله",
]

QUESTIONS = [
    "قیمت یخچال ساید امروز چنده", "کولر گازی ۱۸۰۰۰ موجود داری",
    "لیست جدید رو فرستادی؟", "ماشین لباسشویی چند مدل داری",
    "این ماه تخفیف ویژه‌ای دارین؟", "بار جدید کی می‌رسه",
    "اجاق گاز فردار موجوده؟", "قیمت‌ها تغییری کرده این هفته؟",
    "چند تا برند تلویزیون داری", "همکاری عمده هم انجام می‌دی؟",
    "تسویه نقدی تخفیف داره؟", "ارسال به شهرستان دارین",
    "موجودی انبار به‌روزه؟", "پکیج دیواری هم می‌فروشی",
    "جاروبرقی صنعتی داری", "گارانتی محصولات چطوره",
    "امکان مرجوعی هست؟", "حداقل سفارش چند تاست",
    "فاکتور رسمی می‌دین؟", "کاتالوگ امسال آماده شده؟",
]

CONFIRMATIONS = [
    "بله حتماً در خدمتم", "چشم همین الان می‌فرستم", "آره موجوده",
    "بله بفرمایید", "حتماً، چند لحظه", "درسته همینطوره",
    "بله در خدمت شما هستم", "قربانت، انجام میشه", "بله فردا آماده‌ست",
    "چشم یادداشت کردم", "بله همکاری می‌کنیم", "حتماً پیگیری می‌کنم",
    "بله حله", "درسته، تایید شد", "چشم روی چشم",
]

FOLLOW_UPS = [
    "بعداً بیشتر صحبت می‌کنیم", "فردا هماهنگ می‌کنم باهات",
    "لیست رو شب می‌فرستم", "یه سر بزن فروشگاه", "بعد از ظهر تماس می‌گیرم",
    "قیمت نهایی رو میگم بهت", "هماهنگی رو انجام میدم", "خبرش رو بهت میدم",
    "منتظر جوابت می‌مونم", "پیگیر سفارش هستم", "تا آخر هفته آماده میشه",
    "بارت رو کنار گذاشتم", "به‌محض رسیدن بار خبر میدم", "فاکتور رو آماده می‌کنم",
    "شماره‌ت رو ذخیره کردم",
]

SHOP_TALK = [
    "بازار لوازم خانگی این روزها داغه", "قیمت دلار روی همه چی اثر گذاشته",
    "برند جنرال این فصل فروشش خوبه", "ساید بای ساید تقاضاش بالا رفته",
    "کولر گازی الان فصلشه", "اسنوا و جی‌پلاس بار جدید آوردن",
    "مشتری‌ها دنبال تخفیف نقدی‌ان", "ارسال شهرستان یکم گرون شده",
    "پکیج دیواری فروشش خوب شده", "تلویزیون‌های بزرگ متقاضی داره",
    "اجاق گاز رومیزی زیاد می‌خوان", "لباسشویی دوقلو طرفدار داره",
    "بازار عمده‌فروشی رقابتی شده", "جنس اصل همیشه مشتری داره",
    "گارانتی معتبر خیلی مهم شده", "انبار رو باید شارژ کنیم",
    "تسویه‌ها این ماه بهتر شده", "همکارها بار مشترک می‌گیرن",
    "قیمت‌ها هر روز تغییر می‌کنه", "فروش آنلاین هم راه انداختیم",
    "مشتری وفادار ارزش داره", "کیفیت رو فدای قیمت نمی‌کنیم",
    "بار چینی و ایرانی هر دو داریم", "تنوع محصول زیاد شده",
    "نمایشگاه امسال شلوغ بود",
]

EMOJI_ONLY = [
    "👍", "🙏", "🌹", "😊", "👌", "💪", "🌟", "🔥", "✅", "🤝",
    "👍👍", "🙏🌹", "😊🙏", "💐", "☕", "🌷", "❤️", "👏", "🫡", "🥰",
]

# Slot markers that assemble() fills in.
NAME_SLOT = "{name}"
PRODUCT_SLOT = "{product}"

SLOTTED = [
    "{name} جان، {product} موجوده؟",
    "سلام {name}، قیمت {product} رو داری؟",
    "{name} عزیز، بار {product} کی می‌رسه؟",
    "برای {name} جان بگم که {product} آماده‌ست",
    "{name} جان خسته نباشی، {product} چطوره",
]

PRODUCTS = [
    "یخچال ساید", "کولر گازی", "ماشین لباسشویی", "تلویزیون ۵۵ اینچ",
    "اجاق گاز", "پکیج دیواری", "جاروبرقی", "ماکروویو", "آبگرمکن", "کولر آبی",
]


def _build_pool() -> list[str]:
    """Deterministically assemble a large, de-duplicated Persian phrase pool (>=500)
    from the hardcoded category seeds above. Pure — no RNG, no DB, no network."""
    pool: list[str] = []
    seen: set[str] = set()

    def _add(s: str):
        s = " ".join(s.split()).strip()
        if s and s not in seen:
            seen.add(s)
            pool.append(s)

    # Standalone category entries.
    for lst in (GREETINGS, TIMES_OF_DAY, SMALL_TALK, QUESTIONS, CONFIRMATIONS,
                FOLLOW_UPS, SHOP_TALK, EMOJI_ONLY):
        for s in lst:
            _add(s)

    # greeting × question   (e.g. "سلام، قیمت یخچال ساید امروز چنده")
    for g in GREETINGS:
        for q in QUESTIONS:
            _add(f"{g}، {q}")
    # greeting × small talk
    for g in GREETINGS:
        for s in SMALL_TALK:
            _add(f"{g}، {s}")
    # greeting × shop talk
    for g in GREETINGS[:8]:
        for s in SHOP_TALK:
            _add(f"{g}، {s}")
    # small talk × follow up
    for s in SMALL_TALK[:10]:
        for f in FOLLOW_UPS:
            _add(f"{s}. {f}")
    return pool


# HARDCODED CONSTANT — built once at import from the seeds above. Never DB-dependent.
FALLBACK_PHRASES: list[str] = _build_pool()


def content_hash(text: str) -> str:
    """Stable hash of a normalized message, for per-edge anti-repeat tracking."""
    return hashlib.sha256(normalize_text(text).encode("utf-8")).hexdigest()[:16]


def normalize_text(text: str) -> str:
    """Lowercase-ish normalization: collapse whitespace, strip common punctuation so
    near-duplicates that differ only by spacing/punctuation compare equal."""
    t = (text or "").strip()
    for ch in "،.!?؟…:؛\n\t":
        t = t.replace(ch, " ")
    return " ".join(t.split())


def is_near_duplicate(candidate: str, recent: list[str], threshold: float = 0.82) -> bool:
    """True if `candidate` is an exact or near-duplicate of anything in `recent`
    (difflib ratio on normalized text). Second-defense against repetitive fingerprints."""
    cand = normalize_text(candidate)
    if not cand:
        return True
    for r in recent:
        rn = normalize_text(r)
        if not rn:
            continue
        if cand == rn:
            return True
        if difflib.SequenceMatcher(None, cand, rn).ratio() >= threshold:
            return True
    return False


def _apply_variation(text: str, rng: random.Random) -> str:
    """Light, human-plausible punctuation/emoji variation as a second anti-repeat defense."""
    tails = ["", "", " 🙏", " 👍", " 🌹", ".", " ..."]
    return text + rng.choice(tails)


# V30 PART 5 — emoji presence check for ask/thank-you content (a natural amount is desired).
# Covers the common Unicode emoji ranges (emoticons, symbols/pictographs, transport, supplemental,
# dingbats, misc symbols) plus the frequently-used ✓/❤ variation-selector glyphs.
_EMOJI_RE = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF\U00002190-\U000021FF"
    "\U00002B00-\U00002BFF\U0000FE00-\U0000FE0F\U00002700-\U000027BF]"
)


def has_emoji(text: str | None) -> bool:
    """PURE. True if `text` contains at least one emoji/pictograph glyph."""
    return bool(text) and bool(_EMOJI_RE.search(text))


def _safe_name(name: str | None, rng: random.Random) -> str | None:
    """Guarantee any name used in a message is a realistic human first name — never an
    account number/label. If the caller passed an identifier-looking or unknown value,
    drop it; None means the message simply uses no name."""
    if not name:
        return None
    if looks_like_identifier(name) or name not in HUMAN_NAMES:
        return None
    return name


def assemble_fallback_message(recent_hashes: set[str] | None = None,
                              name: str | None = None,
                              product: str | None = None,
                              rng: random.Random | None = None,
                              forbidden=(),
                              max_tries: int = 40) -> str:
    """Pick a non-repeating fallback phrase (optionally filling name/product slots) that
    is not already in `recent_hashes`. Never touches the DB — works even with an empty
    DB phrase table. Any name is forced through `_safe_name`, and every candidate is
    passed through `message_is_safe` so an internal identifier can never leak."""
    r = rng or random
    recent_hashes = recent_hashes or set()
    name = _safe_name(name, r)

    # Occasionally use a slotted, personalized template.
    use_slot = bool(name) and r.random() < 0.35
    for _ in range(max_tries):
        if use_slot:
            tmpl = r.choice(SLOTTED)
            msg = tmpl.replace(NAME_SLOT, name or "").replace(
                PRODUCT_SLOT, product or r.choice(PRODUCTS))
        else:
            msg = r.choice(FALLBACK_PHRASES)
            if name and r.random() < 0.25:
                msg = f"{name} جان، {msg}"
        msg = _apply_variation(msg, r)
        if content_hash(msg) in recent_hashes or not message_is_safe(msg, forbidden):
            continue
        return msg
    # Extremely unlikely: pool exhausted for this edge — return a plain, safe phrase.
    for _ in range(max_tries):
        msg = _apply_variation(r.choice(FALLBACK_PHRASES), r)
        if message_is_safe(msg, forbidden):
            return msg
    return "سلام وقت بخیر"


async def generate_mesh_message(*, persona: str | None = None,
                                history: list[str] | None = None,
                                recent_hashes: set[str] | None = None,
                                name: str | None = None,
                                product: str | None = None,
                                forbidden=(),
                                ai_fn=None,
                                rng: random.Random | None = None,
                                max_ai_tries: int = 2) -> tuple[str, str]:
    """Generate one mesh message. Returns (text, source) where source is "ai" or
    "fallback". Tries the AI generator first (if provided); on failure, timeout, empty,
    a near-duplicate, or an UNSAFE result (one containing an internal identifier/label),
    falls back to the curated pool. The result is always checked against `recent_hashes`/
    `history` for anti-repeat AND against `message_is_safe` so no identifier ever ships.

    `name` is coerced to a realistic human first name (or dropped) before it reaches the
    AI/fallback, and `history` is pre-filtered to safe lines so a previously-leaked
    identifier in the running conversation can't be echoed back."""
    history = history or []
    recent_hashes = recent_hashes or set()
    r = rng or random
    name = _safe_name(name, r)
    # Never feed an identifier-tainted history line back into the persona/history prompt.
    safe_history = [h for h in history if message_is_safe(h, forbidden)]

    if ai_fn is not None:
        for _ in range(max_ai_tries):
            try:
                text = await ai_fn(persona=persona, history=safe_history, name=name, product=product)
            except Exception as e:
                logger.debug("mesh AI generation failed, will fall back: %s", e)
                break
            if not text or not text.strip():
                break
            text = text.strip()
            if not message_is_safe(text, forbidden):
                logger.debug("mesh AI output contained an identifier/label — rejecting")
                continue  # retry the AI once more before falling back
            if content_hash(text) in recent_hashes or is_near_duplicate(text, safe_history):
                continue  # retry the AI once more before falling back
            return text, "ai"

    return assemble_fallback_message(recent_hashes=recent_hashes, name=name,
                                     product=product, forbidden=forbidden,
                                     rng=r), "fallback"
